# Starship command prompt configuration file. Colour choice and over-use of emoji
# is to help blend in with Ubuntu MATE default theme, Ambiant-Mate.


# disable starship from forcing a new line to be taken. Solved the empty line 
# at start of terminal
add_newline = false

[line_break]
disabled = true

# Replace the "❯" symbol in the prompt with "➟"
[character]      # The name of the module we are configuring is "character"
success_symbol = "  ➟"     # The "symbol" segment is being set to "➜"
error_symbol = "  ✗"


# Hide the username. The username will only show in certain scenarios
[username]
disabled = true

# shows the hostname on new lines
[hostname]
ssh_only = false
trim_at = ".companyname.com"
disabled = false
style = "bold italic #87A752"

# configure directory
[directory]
truncation_length = 10
truncate_to_repo = true # truncates directory to root folder if in github repo
style = "bold italic #87A752"

[cmd_duration]
min_time = 4
show_milliseconds = false
disabled = false
style = "bold italic #87A752"